### ISSUE TITLE
只能爬取到apk信息，不能下载对应APK

### ISSUE THREAD

**Issue by SatoshiZpy** [Ichigo2315/kuan-spider#1]

**Comment by Ichigo2315** [comment]
脚本下载apk的方式是利用selenium + geckodriver驱动firefox浏览器执行自动点击&下载完成后自动跳转到下一个页面，请检查您的设备上是否安装好了同readme中版本的firefox和geckodriver,并更改`pipelines.py` 中的 `driver_path` 项为本地geckodriver的可执行文件的路径。如果仍然报错且无法下载，请提供错误信息

**Comment by SatoshiZpy** [comment]
嗯嗯好像firefox可以，我之前换成chrome是链接下载不了
